name: Deploy to Github Pages automatically

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Installing
      run: npm install
      
    - name: Syncing
      uses: kanadgupta/glitch-sync@master
      with:
        project-id: '${{ secrets.projectId }}'
        auth-token: '${{ secrets.authToken }}'
